### ISSUE TITLE
`com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon`

### ISSUE THREAD

**Issue by stdedos** [osimek1/intellij-code-blocks-sorter#18]
tl;dr like [leinardi/mypy-pycharm@`eb9e007` (#123)](https://github.com/leinardi/mypy-pycharm/pull/123/commits/eb9e00747868383cb7b8b110780a6e6deed827c8)

**Comment by coldham10** [comment]
Reporting the same, with stack trace:
```
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'eu.osimowicz.plugins.intellij.actions.SortCodeBlockCaseInsensitiveAction' must override `getActionUpdateThread()` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: eu.osimowicz.plugins.intellij.CodeBlocksSorter]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:201)
```
